#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_0_IS_DUAL 0x1
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x10
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_0_IS_DUAL 0x1

/*  BOARD definition */
#define XPS_BOARD_NEXYS4


/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_RISCV_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 1
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_I_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_I_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_I_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_I_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */