domain_path: C:\Users\mamin\Documents\GitHub\Nexys4_bringup\nexys4_microblazeV\export\nexys4_microblazeV\sw\standalone_microblaze_riscv_0
app_src_dir: C:\AMDDesignTools\2026.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
